language: node_js
node_js:
- '9'
dist: trusty
services:
- mongodb
env:
- NODE_ENV=production
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: poxnwNt3hz2zo6bAOzxQrn/w0OZwph9qBe1uJd7B57nsIgU2Y/2a+KT7FxrE9RMfyaktAq1jSxnnrmmnHOuoexWRV/MVkVz/Ifsbzgi//1itWV7Wn4yMEuFzxoCVWKGK2YZDJwQnX2LX5Ep6z1/uKwkoLqFVIekJbJRitsg+B8dvJp1C3SlPAjylqXQySbGklrorY+G+TAnCOTfkWLkVfsgkBZLynnUDSPJZvUHjhqrLl2I70vZzYNgHZtVcMUlwk2X5HsMZW8yIG1vc/gs+SrfEIDu/qTZyG/rQOI42hlsYLGwu8H7OSc5p60M5eWuIr0IqnmdzL7czbWEGuPPhL1cUSaQheUtfICnkorEN8llmwCwnsqGSHpUZ16FHUHBmjx6Vm/lktYuXDAdq85hxiAIJdyIXoO/cu0Njy/dpmGQfdFbcM5tSKAJ1TXVNQvat4lfAO5aJx7/CtduPKdxfy+uBP3m0aHq9uIFPXuf5lPbWgiLlJdNLgMVFl1pQY8SCJdXFwf+LskV2pMV5CmQg7iWi8QA92KNwjLiKMN4/wXJLiHkcUewSmi/+9H+fRCjkP1wp6HlZ+Mkiglj3LpuEcEv+qxogGL6RaQhihpa4CHEqpKqrbjMSge1vbl+V+mwjsAQkvIewZVtuuLQiTqse7tXaAR0Ynge+IF41a68Gqn8=
  app: sk-node200-loopback-workshop
  on:
    repo: SKtaeji/startnow-node200-loopback-workshop
