language: node_js
node_js:
- '9'
dist: trusty
services:
- mongodb
env:
- NODE_ENV=production
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: jOficgLbUqLwe1hMfAbZe5fOhHqA0bGFY3vJylRprH5EGMhs90XGbJQm2PxbLdQQgWj9i/S20nUZuMvm7WW+QEq/YQNnjjHaFRwMSRGGyDUUCpIZIf/BB2pCBVPeysSyaEKCMrxY+QEuPbRGwHEJrM50Ff7sGCnMaSQmiAOeXsI1vLf3Pd3lUtnVW/LqWO/GDfkOJwcWjerTIVsb6NubK0syKmvGrNIvr6lg99haZgZXdORdhvenJvCqetY5hDRNhB46rUulnBQOsRQJp3vSMV8oBvcUWmrMp3IyDWgN1TAKBVy3fV5dxQ5I/PRRVLRWpzESsll91FLe+c/FHPwKfD8CBadwB4cH44eMDF3ixlKD3VeRWuiAoREP9jtjw7AnSWOli2IXAFXiaw+90jxpb6tDXTTMimKBLVHpjjQZGuRBcJkqKHH9uvlOCSDTfG5zJpaKeK2PcP85ahLov/7tRrdpZPtqW0gM6u3svzMWQEdqOi8Y3NLQWEOmASMXaw6j6PlH3LaWNpdO58KZEYJ+KIVJZatJcnZqGpOjuYciVFwOzGKFm5XoNPt+D/BBwM7YNmL1mMNQwU92Fwz4AakxPM3X6AUT9Esd2+yHcr4+Q3JJmCc7S3TPuxELpbBZsBTafBdouMFA9BubDiZldTYylLpbDI4pFPilivIC2Ut+DGw=
  app: sk-node200-loopback-workshop
  on:
    repo: SKtaeji/startnow-node200-loopback-workshop
